# Raw food item price analysis for June 2023

In [12]:
import numpy as np
import pandas as pd

#!pip install pandas fastparquet

URL_DATA = 'https://storage.googleapis.com/dosm-public-pricecatcher/pricecatcher_2023-06.parquet'

df = pd.read_parquet(URL_DATA)
if 'date' in df.columns: df['date'] = pd.to_datetime(df['date'])

df.head()

        date  premise_code  item_code  price
0 2023-06-01             2          1    9.4
1 2023-06-01             2          9   36.0
2 2023-06-01             2         16    4.8
3 2023-06-01             2         18    5.5
4 2023-06-01             2         19    5.5

In [13]:
URL_DATA = 'https://storage.googleapis.com/dosm-public-pricecatcher/lookup_premise.parquet'
df_premise_code = pd.read_parquet(URL_DATA)
if 'date' in df_premise_code.columns: df_premise_code['date'] = pd.to_datetime(df_premise_code['date'])

df_premise_code.head(10)

,premise_code,premise,address,premise_type,state,district
0,-1,None,",",None,None,None
1,2,PASAR BESAR IPOH,"JALAN LAKSAMANA,TAMAN JUBILEE,30300 IPOH, PERAK",Pasar Basah,Perak,Kinta
2,3,JUSCO AYER KEROH,"LOT 4991,MUKIM BUKIT BARU,75450 LEBUH AYER KER...",Pasar Raya / Supermarket,Melaka,Melaka Tengah
3,6,KEDAI RUNCIT TAFAZ MAJU PRESINT 9,"NO.5, JALAN P9B/1,PRESINT 9,62250 PUTRAJAYA",Kedai Runcit,W.P. Putrajaya,Wp Putrajaya
4,7,KEDAI RUNCIT SYAZ MAJU PRESINT 9,"NO.5, JALAN P9E/1,PRESINT 9,62250 PUTRAJAYA",Kedai Runcit,W.P. Putrajaya,Wp Putrajaya
5,8,PASAR MINI D'MART PRESINT 8,"BLOK A T00/U01,JALAN P8/D,PRESINT 8, 62000 PUT...",Pasar Mini,W.P. Putrajaya,Wp Putrajaya
6,15,PASAR MINI KARIM,"NO, 7A,KAWASAN PASAR UTAN AJI,01000 KANGAR, PE...",Kedai Runcit,Perlis,Kangar
7,16,PASARAYA K-CERIA (KANGAR) SDN. BHD,"NO 3, 5, 7 & 9,JALAN KANGAR - ALOR SETAR SERIA...",Pasar Raya / Supermarket,Perlis,Kangar
8,115,TAMPIN SHOPPING CENTRE,"NO 111,JALAN BESAR,73000 TAMPIN, NEGERI SEMBILAN.",Pasar Raya / Supermarket,Negeri Sembilan,Tampin
9,136,THE STORE ( PUDU PLAZA ),"UG & 1st FLOOR, PUDU PLAZA,JALAN DAVIS,",Pasar Raya / Supermarket,W.P. Kuala Lumpur,Cheras

In [14]:
print(f' There are {df_premise_code["district"].nunique()} district')
df_premise_code['district'].unique()

 There are 173 district

array([None, 'Kinta', 'Melaka Tengah', 'Wp Putrajaya', 'Kangar', 'Tampin',
       'Cheras', 'Seremban', 'Petaling Jaya', 'Tuaran',
       'Larut, Matang & Selama', 'Petaling', 'Kawasan Luar Bandar',
       'Kota Bharu', 'Kota Setar', 'Bintulu', 'Tamparuli', 'Kuala Krai',
       'Bau', 'Arau', 'Padang Besar', 'Tumpat', 'Seputeh', 'Setiawangsa',
       'Lembah Pantai', 'Gua Musang', 'Pasir Puteh', 'Bachok', 'Batu',
       'Tanah Merah', 'Pontian', 'Mersing', 'Johor Bahru', 'Kota Tinggi',
       'Gemas', 'Kawasan Bandar', 'Pasir Mas', 'Serian', 'Kuching',
       'Keningau', 'Tambunan', 'Beaufort', 'Tenom', 'Sipitang',
       'Kuala Penyu', 'Kuala Pilah', 'Bahau', 'Rompin', 'Muar',
       'Batu Pahat', 'Sri Aman', 'Kudat', 'Kuala Kangsar', 'Muallim',
       'Batang Padang', 'Segamat', 'Hulu Perak', 'Pendang', 'Pokok Sena',
       'Kerian', 'Kapit', 'Belaga', 'Song', 'Jeli', 'Alor Gajah',
       'Machang', 'Hilir Perak', 'Meradong', 'Julau', 'Sandakan',
       'Sarikei', 'Saratok', 'Kota Belud', 'Barat Daya', 'Timur Laut',
       'Johol', 'Tawau', 'Kampar', 'Kota Kinabalu', 'Semporna',
       'Kuala Terengganu', 'Papar', 'Penampang', 'Putatan', 'Rembau',
       'Kota Marudu', 'Kalabakan', 'Langkawi', 'Kubang Pasu',
       'Port Dickson', 'Lundu', 'Pitas', 'Jasin', 'Titiwangsa',
       'Lahad Datu', 'Limbang', 'Kuala Nerus', 'Sibu', 'Lawas', 'Kluang',
       'Sik', 'Setiu', 'Kulim', 'Besut', 'Temerloh', 'Dungun', 'Baling',
       'Bera', 'Klang', 'Jerantut', 'Kepong', 'Hulu Terengganu', 'Gombak',
       'Perak Tengah', 'Segambut', 'Jelebu', 'Maran', 'Kuala Selangor',
       'Sabak Bernam', 'Ranau', 'Kanowit', 'Sibujaya', 'Kunak',
       'Hulu Langat', 'Padang Terap', 'Tatau', 'Rawang',
       'Seberang Perai Tengah', 'Seberang Perai Utara', 'Yan', 'Sebauh',
       'Kuantan', 'Manjung', 'Lubok Antu', 'Seberang Perai Selatan',
       'Lipis', 'Kuala Muda', 'Bekenu', 'Bandar Tun Razak', 'Miri',
       'Bagan Datuk', 'Wangsa Maju', 'Pekan', 'Raub', 'Bentong', 'Mukah',
       'Dalat', 'Batu Niah', 'Marudi', 'Kota Padawan', 'Kuala Langat',
       'Kemaman', 'Marang', 'Sepang', 'Engkelili', 'Bukit Bintang',
       'Hulu Selangor', 'Kota Samarahan', 'Ledang', 'Dabong', 'Betong',
       'Pakan', 'Selangau', 'Cameron Highlands', 'Kimanis',
       'Tanjung Manis', 'Balingian', 'Lojing', 'Tangkak', 'Parit Buntar',
       'Gerik', 'Tapah', 'Nabawan', 'Cyberjaya'], dtype=object)

In [16]:
df_premise_code[df_premise_code['district']=='Kangar'].nunique()

premise_code    27
premise         27
address         27
premise_type    10
state            1
district         1
dtype: int64

In [4]:
URL_DATA = 'https://storage.googleapis.com/dosm-public-pricecatcher/lookup_item.parquet'
df_item_code = pd.read_parquet(URL_DATA)
if 'date' in df_item_code.columns: df_item_code['date'] = pd.to_datetime(df_item_code['date'])
df_item_code.head()

,item_code,item,unit,item_group,item_category
0,-1,None,None,None,None
1,1,AYAM BERSIH - STANDARD,1kg,BARANGAN SEGAR,AYAM
2,2,AYAM BERSIH - SUPER,1kg,BARANGAN SEGAR,AYAM
3,3,AYAM HIDUP,1kg,BARANGAN SEGAR,AYAM
4,9,DAGING KAMBING BEBIRI IMPORT BERTULANG (MUTTON...,1kg,BARANGAN SEGAR,DAGING